
"use client"
import React, { useEffect, useRef } from "react"

/**
 * LiquidEffect Component
 * Provides a high-fidelity, cursor-reactive liquid surface.
 * Optimized for cinematic interfaces with a "static-until-touched" behavior.
 */
export function LiquidEffect() {
  const canvasRef = useRef<HTMLCanvasElement>(null)

  useEffect(() => {
    if (!canvasRef.current) return

    const script = document.createElement("script")
    script.type = "module"
    script.textContent = `
      import LiquidBackground from 'https://cdn.jsdelivr.net/npm/threejs-components@0.0.22/build/backgrounds/liquid1.min.js';
      const canvas = document.getElementById('liquid-canvas');
      
      if (canvas) {
        // Initialize the liquid background component
        const app = LiquidBackground(canvas);
        
        // Load a deep, architectural texture
        app.loadImage('https://images.unsplash.com/photo-1557683311-eac922347aa1?auto=format&fit=crop&q=80&w=2564');
        
        // SURFACE PHYSICS & AESTHETICS
        // Creating a "Mercurial Glass" effect:
        app.liquidPlane.material.metalness = 0.95;   // High reflectivity
        app.liquidPlane.material.roughness = 0.02;   // Ultra-smooth surface
        app.liquidPlane.material.transparent = true;
        app.liquidPlane.material.opacity = 0.25;      // Subtle enough to not distract from content
        
        // INTERACTION TUNING
        // Increases the height of the waves generated by cursor movement
        app.liquidPlane.uniforms.displacementScale.value = 6.0;
        
        // MOTION STABILITY LOCK
        // By default, this component flows over time. For Voidyx, we want it 
        // to be a "Void"—completely still unless the user interacts.
        const originalRender = app.render;
        app.render = () => {
          // Zero out time-based uniforms every frame to freeze the "flow"
          if (app.liquidPlane.uniforms.uTime) app.liquidPlane.uniforms.uTime.value = 0.0;
          if (app.liquidPlane.uniforms.time) app.liquidPlane.uniforms.time.value = 0.0;
          if (app.liquidPlane.uniforms.interval) app.liquidPlane.uniforms.interval.value = 0.0;
          
          originalRender();
        };

        window.__liquidApp = app;
      }
    `;
    document.body.appendChild(script)

    return () => {
      // Cleanup Three.js resources and scripts on unmount
      if (window.__liquidApp && typeof window.__liquidApp.dispose === 'function') {
        window.__liquidApp.dispose()
      }
      if (script.parentNode) {
        document.body.removeChild(script)
      }
    }
  }, [])

  return (
    <div className="fixed inset-0 m-0 w-full h-full touch-none overflow-hidden z-0 pointer-events-none bg-[#050505]">
      <canvas 
        ref={canvasRef} 
        id="liquid-canvas" 
        className="fixed inset-0 w-full h-full opacity-40" 
      />
      {/* 
          Vignette and Color Wash layer: 
          Adds depth and ensures text remains legible over the simulation.
      */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#050505]/20 to-[#050505] pointer-events-none" />
      <div className="absolute inset-0 bg-[#050505]/40 pointer-events-none" />
    </div>
  )
}

declare global {
  interface Window {
    __liquidApp?: any
  }
}
